#!/bin/sh
# porting debian script to yocto initramfs-framework
# a better idea is to have a compatible env 
# or even better install arm package onto rootfs

nbdrootfs_enabled() {
	echo "root(${bootparam_root}) nbdroot(${bootparam_nbdroot})"
	if [ -z ${bootparam_nbdroot} ]; then
		echo "Empty nbdroot!"
		return 1
	fi

	case "${bootparam_root}" in /dev/nbd*)
		echo "Found nbdroot and root!"
		return 0
	esac

	echo "root has no nbd dev"
	return 1
}

nbdrootfs_run() {
	local nbdrootdev
	local nbdbasedev
	local nbdroot
	local nbdsrv
	local nbdpath
	local nbdport
	local nbdportpath

	nbdrootdev="$bootparam_root"
	nbdbasedev="${bootparam_root#/dev/}"
	nbdroot="$bootparam_nbdroot"

	case "$nbdroot" in
		*,*,*)
			nbdsrv="${nbdroot%%,*}"
			nbdpath="${nbdroot%,*}"
			nbdpath="${nbdpath##*,}"
			# root= parameter overrides three-option nbdroot= parameter
			if [ -z "$nbdrootdev" ]
			then
				nbdbasedev="${nbdroot##*,}"
				nbdrootdev=/dev/$nbdbasedev
			fi
			;;
		*,*)
			nbdsrv="${nbdroot%,*}"
			nbdport="${nbdroot#*,}"
			;;
		\[*\]:/*)
			# [ipv6]:/path
			# Note: this is specifically written to be compatible with NFS
			# URLs
			nbdsrv=${nbdroot%\]*}
			nbdsrv=${nbdsrv#\[}
			nbdpath=${nbdroot#\[$nbdsrv\]}
			nbdpath=${nbdpath#:}
			;;
		\[*\]*)
			# [ipv6]:port/path
			nbdsrv=${nbdroot%\]*}
			nbdsrv=${nbdsrv#\[}
			nbdportpath=${nbdroot#\[$nbdsrv\]}
			nbdportpath=${nbdportpath#:}
			nbdport=${nbdportpath%%/*}
			nbdpath=${nbdportpath#$nbdport/}
			;;
		/*|*:/*)
			# ipv4:/path
			# Note: this is specifically written to be compatible with NFS
			# URLs
			nbdsrv=${nbdroot%%[:/]*}
			nbdpath=${nbdroot#$nbdsrv}
			nbdpath=${nbdpath#:}
			;;
		*)
			# ipv4:port/path
			nbdsrv=${nbdroot%%[:/]*}
			nbdportpath=${nbdroot#$nbdsrv}
			nbdportpath=${nbdportpath#:}
			nbdport=${nbdportpath%%/*}
			nbdpath=${nbdportpath#$nbdport/}
			;;
	esac

	nbdrootdev=${nbdrootdev%p*}
	nbdbasedev=${nbdbasedev%p*}

	if [ -z "$nbdsrv" ] || [ -z "$nbdrootdev" ] || [ -z "$nbdpath" ]
	then
		echo "Insufficient information to set up nbd, quitting (nbdroot=$nbdroot, host=$nbdsrv, name=$nbdpath, port=$nbdport, nbd-device=$nbdrootdev)"
		return 1
	fi

	# Support defining an alternate launch script with env variable NBDCLIENT.
	#NBDCLIENT=${NBDCLIENT:-/sbin/nbd-client}
	# initramfs image install the program into /usr/sbin
	NBDCLIENT=nbd-client
	echo $NBDCLIENT $nbdsrv -N $nbdpath $nbdport $nbdrootdev -swap -persist -systemd-mark
	echo mount ${nbdrootdev} ${ROOTFS_DIR}

	[ -n "${ROOTFS_DIR}" ] && {
		echo "ROOTFS_DIR not empty! ${ROOTFS_DIR}"
		# Now nbd is embedded into kernel
		# because initramfs even does not have module dir
		# More generally should be linked to kernel config
		# load_kernel_module nbd
		$NBDCLIENT $nbdsrv -N $nbdpath $nbdport $nbdrootdev -swap -persist -systemd-mark
		mount ${nbdrootdev} ${ROOTFS_DIR}
	}
}

[ -z "${ROOTFS_DIR}" ] && {
	echo "Built in test started (init script fragment)"
	module="nbdrootfs"
	bootparam_root=/dev/nbd0
	bootparam_nbdroot=10.0.2.2:10809/rootfs.img
        if ! eval "${module}_enabled"; then
                echo "Skipping module $module"
		exit 1
        fi

        echo "Running ${module}_run"
        eval "${module}_run"
}
